version: '3.4'

services:
  cli:
    extends:
      file: compose.yaml
      service: cli
    build:
      target: composer
      args:
        COMPOSER_BASE: development
    working_dir: /app
    volumes:
      - ./app:/app:cached
    environment:
      STAGE: dev

  db:
    extends:
      file: compose.yaml
      service: db
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB_NAME: test
